name: Build and Deploy to GKE (Artifact Registry)

on:
  push:
    branches: [main]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us
  REPO_NAME: flask-gke-demo
  IMAGE: us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/flask-gke-demo/flask-gke-demo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Docker to use Artifact Registry
      run: |
        gcloud auth configure-docker us-docker.pkg.dev --quiet

    - name: Build and Push Docker image
      run: |
        docker build -t $IMAGE:$GITHUB_SHA .
        docker push $IMAGE:$GITHUB_SHA

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
        location: ${{ secrets.GKE_ZONE }}

    - name: Deploy to GKE
      run: |
        sed "s|IMAGE_PLACEHOLDER|$IMAGE:$GITHUB_SHA|" k8s/deployment.yaml | kubectl apply -f -
